# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Permalinks
permalink:        pretty

# Setup
title:            John's Awesome Blog
tagline:          It's Awesome!
description: >-
  There are probably words and stuff.
url:              https://djspinmonkey.github.io
baseurl:          ""
exclude:
  - README.md

# defaults to first paragraph (\n\n)
# uncomment to switch to explicit separator
# excerpt_separator: "<!-- more -->"

author:
  name:           'John Hyland'
  url:            https://djspinmonkey.github.io

paginate:         5

jekyll_compose:
    auto_open: true
