# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Permalinks
permalink:        pretty

# Setup
title:            John's Awesome Blog
tagline:          It's Awesome!
description: >-
  There are probably words and stuff.
url:              https://djspinmonkey.github.io/
baseurl:          /

author:
  name:           'John Hyland'
  url:            https://djspinmonkey.github.io

paginate:         5

jekyll_compose:
    auto_open: true
